BethanyPieShop2/BethanyPieShop2/Models/ProductDetail.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BethanyPieShop2.Models
{
    public class ProductDetail
    {
        [Key]
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        [Required]
        public double Price { get; set; }


        public string ImagePath { get; set; }
        public Category Catagory { get; set; }
        public int CatagoryId { get; set; }
    }
}

BethanyPieShop2/BethanyPieShop2/Controllers/CartController.cs
using BethanyPieShop2.Models;
using BethanyPieShop2.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BethanyPieShop2.Controllers
{
    public class CartController : Controller
    {
        DbContextClass _context;
        List<ProductViewModel> cart;
        Address ad = new Address();
        // OrderDetail pl = new OrderDetail();


        public CartController()
        {
            _context = new DbContextClass();
            cart = new List<ProductViewModel>();

        }
        // GET: Cart
        public ActionResult Index()
        {

            return View();
        }
        public ActionResult Buy(int id)
        {
            var singleProduct = _context.ProductDetails.SingleOrDefault(c => c.ProductId == id);


            if (Session["cart"] == null)
            {
                cart.Add(new ProductViewModel { ProductDetails = singleProduct, Quantity = 1 });
                Session["cart"] = cart;
            }
            else
            {
                List<ProductViewModel> cart = (List<ProductViewModel>)Session["cart"];
                int index = isExist(id);
                if (index != -1)
                {
                    cart[index].Quantity++;
                }
                else
                {

                    cart.Add(new ProductViewModel { ProductDetails = singleProduct, Quantity = 1 });
                }
                Session["cart"] = cart;
            }
            return RedirectToAction("Index", cart);
        }

        //public ActionResult Order(ProductDetail p)
        //{
        //  //  orderDetail();
        //    return RedirectToAction("Address", cart);
        //}


        private int isExist(int id)
        {
            List<ProductViewModel> cart = (List<ProductViewModel>)Session["cart"];
            for (int i = 0; i < cart.Count; i++)
                if (cart[i].ProductDetails.ProductId.Equals(id))
                    return i;
            return -1;
        }


        public ActionResult Address()
        {
            return View();
        }

        public ActionResult Address2()
        {
        //    string single = (string)Session["FName"];
        //    var singleCustomer = _context.Addresses.Find(single);
            Address1();
            return View();
        }

        [HttpPost]
        public ActionResult Address1()
        {
            // Address ad = _context.Addresses.SingleOrDefault(c => c.UserId == Session["UserId"]);
            // ad.UserId = Session["UserId"];
            // ad.Register = 0;
            ad.UserId = Convert.ToInt32(Request.Form["UserId"]);
            ad.Country = (Request.Form["Country"]);
            ad.LName = (Request.Form["LName"]);
            ad.FName = (Request.Form["FName"]);
            ad.PhoneNo = (Request.Form["PhoneNo"]);
            ad.State = (Request.Form["State"]);
            ad.Zipcode = Convert.ToInt64(Request.Form["Zipcode"]);
            ad.Address1 = (Request.Form["Address1"]);
            ad.Address2 = (Request.Form["Address2"]);
            ad.City = (Request.Form["City"]);
            ad.EmailId = (Request.Form["EmailId"]);
            _context.Addresses.Add(ad);
            _context.SaveChanges();
            return View("Address");
            //return RedirectToAction("OrderDetail", cart);

        }
        [HttpPost]
        public ActionResult orderDetail(IEnumerable<BethanyPieShop2.Models.ProductDetail> pl)
        {


            if (Session["username"] == null)
            {
                return RedirectToAction("Register", "Users", new { area = "Admin" });
            }
            else
            {
                var pl1 = (List<BethanyPieShop2.ViewModel.ProductViewModel>)Session["cart"];
                // _context.OrderDetails.AddRange(pl);                     // Data Binding
                //_context.Set<ProductDetail>().AddOrUpdate(product);
                //    _context.SaveChanges();
                return RedirectToAction("Address", cart);
            }
        }

        public ActionResult ConfirmOrder()
        {
            return View();
        }

    }
}

BethanyPieShop2/BethanyPieShop2/Controllers/ProductDetailsController.cs
using BethanyPieShop2.Models;
using BethanyPieShop2.ViewModel;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BethanyPieShop2.Controllers
{
    public class ProductDetailsController : Controller
    {
        // GET: ProductDetails
        DbContextClass _context;
        public ProductDetailsController()
        {
            _context = new DbContextClass();

        }
        public ActionResult Index()
        {

            var allPies = _context.ProductDetails.Where(p => p.CatagoryId==1)
                .OrderBy(p => p.ProductName);
            return View(allPies);

        }
        public ActionResult ApplePie(int id)
        {
            var CatPie = _context.ProductDetails.Include(c => c.Catagory).Where(p => p.CatagoryId == id);

            return View(CatPie);
        }
        public ActionResult PumpkinPie()
        {
            return View();
        }
        public ActionResult RhubarbPie()
        {
            return View();
        }



        //// GET: ProductDetails
        //public ActionResult Index()
        //{
        //    var products = _context.ProductDetails.ToList();
        //    return View(products);
        //}

        //public ActionResult Details(int id)
        //{
        //    var singleProduct = _context.ProductDetails.SingleOrDefault(k => k.ProductId == id);
        //    if (singleProduct == null)
        //        return HttpNotFound();
        //    return View(singleProduct);
        //}

        //public ActionResult Update(int? id)
        //{
        //    var updateProduct = _context.ProductDetails.SingleOrDefault(c => c.ProductId == id);
        //    if (updateProduct == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    var up = new ProDetailsAndCatagory
        //    {
        //        ProductDetail = updateProduct,
        //        Catagories = _context.Categories.ToList()
        //    };
        //    return View("Create", up);
        //}

        //public ActionResult Create()
        //{
        //    var newCatagory = _context.Categories.ToList();
        //    var viewModel = new ProDetailsAndCatagory
        //    {
        //        Catagories = newCatagory
        //        //ProductDetail = new ProductDetail()
        //    };
        //    return View(viewModel);
        //}

        //[HttpPost]
        //public ActionResult Create(ProductDetail product)
        //{
        //    _context.ProductDetails.Add(product);                      // Data Binding
        //    //_context.Set<ProductDetail>().AddOrUpdate(product);
        //    _context.SaveChanges();
        //    //try
        //    //{
        //    //	_context.SaveChanges();
        //    //}
        //    //catch (DbEntityValidationException e)
        //    //{
        //    //             Console.WriteLine(e);
        //    //}

        //    return RedirectToAction("Index", "ProductDetails");
        //}

        //public ActionResult Delete(int? id)
        //{
        //    var selectProduct = _context.ProductDetails.SingleOrDefault(c => c.ProductId == id);
        //    if (selectProduct == null)
        //        return HttpNotFound();
        //    _context.ProductDetails.Remove(selectProduct);
        //    _context.SaveChanges();
        //    return RedirectToAction("Index", "ProductDetails");
        //}
    }
}

BethanyPieShop2/BethanyPieShop2/Views/ProductDetails/ApplePie.cshtml
@{
    ViewBag.Title = "ApplePie";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model IEnumerable<BethanyPieShop2.Models.ProductDetail>

    @foreach(var a in Model)
    { 
 
                    <h3>Apple Pie</h3>
                    <div class="card" style="margin-bottom:15px">
                        <img class="card-img-top" src="~/Images/@a.ImagePath" alt="Card image cap">
                        <div class="card-body">
                            <div class="row card-header">
                                <span class="card-title">
                                    <p class="pie-header">@a.ProductName</p>
                                </span>
                                <span class="card-value">@a.Price</span>
                            </div>
                            <p class="card-text">Our famous apple pies!</p>
                            <p>I’m not entirely sure. But I do know that I like apples. And more than apples, I like pie. I’ve yet to find a flaky, succulent circle of happiness that I wasn’t eager to shovel into my mouth; from rhubarb to arguably the best pie on earth — chicken pot pie. So, for this week’s taste test, D Magazine staffers tried a handful of apple pies from grocery stores in town. I didn’t think it would be fair to include luscious, gourmet pies — I’m talking to you Emporium — in the ranking.  The pies varied in texture, flavor and price</p>
                            <a href="#" class="btn add-cart">Add t
                        </div>
                        </div>
          }

BethanyPieShop2/BethanyPieShop2/Views/ProductDetails/Create.cshtml
@model BethanyPieShop2.ViewModel.ProDetailsAndCatagory
@{
    ViewBag.Title = "Create";
}

<h2>New Product</h2>
@using (Html.BeginForm("Create", "ProductDetails"))
{
    <div class="form-group">
        @Html.Label("Product Name")
        @Html.TextBoxFor(c => c.ProductDetail.ProductName, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.Label("Short Description")
        @Html.TextBoxFor(m => m.ProductDetail.ShortDescription, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.Label("Type Of Pie")
        @Html.DropDownListFor(c => c.ProductDetail.CatagoryId, new SelectList(Model.Catagories, "Id", "PieType"), " ", new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.Label("Long Description")
        @Html.TextBoxFor(m => m.ProductDetail.LongDescription, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.Label("Image")
        @Html.TextBoxFor(v => v.ProductDetail.Image, new { @type = "file", @class = "form - control" })

    </div>

    <div class="form-group">
        @Html.Label("Price")
        @Html.TextBoxFor(c => c.ProductDetail.Price, new { @class = "form-control" })
    </div>

    @*@Html.HiddenFor(m => m.ProductDetail.ProductId)*@

    <button type="submit" class="btn btn-primary">Insert</button>
}

BethanyPieShop2/BethanyPieShop2/Views/ProductDetails/Index.cshtml
@model IEnumerable<BethanyPieShop2.Models.ProductDetail>

@{ ViewBag.Title = "Index";
                Layout = "~/Views/Shared/_Layout.cshtml"; }

<section>
    <div class="container" style="margin-top:20px">
        <div class="mainContent">
            <div class="row">
                <div class="col-md-3">
                    <aside class="leftmenu">
                        <a href="index.html"><img  class="logoleft" src="~/Images/Logo.png" /></a>
                    </aside>
                </div>
                <div class="col-md-9">
                    <article>
                        <figure>
                            <img src="~/Images/bethany-fullsize.jpg" width="850" alt="bethany in her pie shop" />
                        </figure>

                    </article>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">

                </div>
                <div class="col-md-9">
                    <div class="pie-label">Pies of the Week</div>
                    <div class="small">Our weekly selection- just for you!</div>
                    <div class="row cards-container">
                        @foreach (var item in Model)
                        {
            <div class="col-md-4" style="margin-bottom:5px;">
                <div class="card">
                    <img class="card-img-top" src="~/@item.ImagePath" alt="Card image cap">
                    <div class="card-body">
                        <div class="row card-header">
                            <span class="card-title">
                                @Html.ActionLink(@item.ShortDescription, @item.ProductName, "ProductDetails", new { @class = "pie-header" })
                            </span>
                            <span class="card-value">@item.Price</span>
                        </div>
                        <p class="card-text">@item.LongDescription</p>
                        @*@Html.ActionLink("Add to cart", "Buy", "Cart", new { @class = "btn add-cart" })*@
                    <li class="glyphicon glyphicon-shopping-cart"></li>
                        <a href="@Url.Action("Buy", "Cart", new { id = item.ProductId })">Add To Cart</a>
                    
                        @*<a href="#" class="btn add-cart">Add to cart</a>*@
                      

                    </div>
                </div>
            </div>}


                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

BethanyPieShop2/BethanyPieShop2/Views/ProductDetails/New.cshtml
@model BethanyPieShop2.ViewModel.ProDetailsAndCatagory
@{
    ViewBag.Title = "New";
}

<h2>New Product</h2>
@using (Html.BeginForm("Create", "ProductDetails"))
{
    <div class="form-group">
        @Html.Label("Product Name")
        @Html.TextBoxFor(c => c.ProductDetail.ProductName, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.Label("Short Description")
        @Html.TextBoxFor(m => m.ProductDetail.ShortDescription, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.Label("Type Of Pie")
        @Html.DropDownListFor(c => c.ProductDetail.CatagoryId, new SelectList(Model.Catagories, "Id", "PieType"), " ", new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.Label("Long Description")
        @Html.TextBoxFor(m => m.ProductDetail.LongDescription, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.Label("Image")
        @Html.TextBoxFor(v => v.ProductDetail.Image, new { @type = "file", @class = "form - control" })

    </div>

    <div class="form-group">
        @Html.Label("Price")
        @Html.TextBoxFor(c => c.ProductDetail.Price, new { @class = "form-control" })
    </div>

    @*@Html.HiddenFor(m => m.ProductDetail.ProductId)*@

    <button type="submit" class="btn btn-primary">Insert</button>
}

BethanyPieShop2/BethanyPieShop2/Views/ProductDetails/PumpkinPie.cshtml
@{
    ViewBag.Title = "PumpkinPie";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section>
    <div class="container" @*style="margin-top:15px"*@>
        <div class="mainContent">
            <div class="row">
                <div class="col-md-3">
                    <aside class="leftmenu">
                        <a href="index.html"><img src="~/Images/bethanylogo.png" /></a>
                    </aside>
                </div>

                <div class="col-md-9">
                    <h3>Pumpkin Pie</h3>
                    <div class="card" style="margin-bottom:15px">
                        <img class="card-img-top" src="~/Images/products/pumpkinpiesmall.jpg" alt="Card image cap">
                        <div class="card-body">
                            <div class="row card-header">
                                <span class="card-title">
                                    <p class="pie-header">Pumpkin Pie</p>
                                </span>
                                <span class="card-value">12.75$</span>
                            </div>
                            <p class="card-text">Ok, pumpkin pie topped with a huge serving a whipped cream.  Today’s recipe is my absolute favorite recipe for homemade pumpkin pie.  One bite and you’ll be wondering why you’ve never made your own pumpkin pie at home. </p>
                            <a href="#" class="btn add-cart">Add to cart</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

BethanyPieShop2/BethanyPieShop2/Views/ProductDetails/RhubarbPie.cshtml
@{
    ViewBag.Title = "RhubarbPie";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<section>
    <div class="container" style="margin-top:-22px">
        <div class="mainContent">
            <div class="row">
                <div class="col-md-3">
                    <aside class="leftmenu">
                        <a href="index.html"><img src="~/Images/bethanylogo.png" /></a>
                    </aside>
                </div>

                <div class="col-md-9">
                    <h3>Rhubarb Pie</h3>
                    <div class="card" style="margin-bottom:15px">
                        <img class="card-img-top" src="~/Images/products/rhubarbpiesmall.jpg" alt="Card image cap">
                        <div class="card-body">
                            <div class="row card-header">
                                <span class="card-title">
                                    <p class="pie-header">Rhubarb Pie</p>
                                </span>
                                <span class="card-value">40.75$</span>
                            </div>
                            <p class="card-text">Our famous apple pies!</p>
                            <p>Delicious succulent with the clear juicy flavors of strawberry and rhubarb. I like that this recipe is the simplest of these pies. I skipped the lemon juice because it seemed plenty tart to me - but maybe this is for color. </p>
                            <a href="#" class="btn add-cart">Add to cart</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>